import AppKit
import CueCore

/// All pasteboard objects and timer state stay on this private serial queue.
/// Reading a promised pasteboard payload may wait on another app; it must never block typing.
final class ClipboardMonitor: @unchecked Sendable {
    enum Event: Sendable {
        case captured(String, generation: Int)
        case accessDenied(generation: Int)
    }

    static let ownMarker = NSPasteboard.PasteboardType("com.yyhsiu.cue.clipboard-history")
    private static let ignoredTypes: Set<String> = [
        ownMarker.rawValue,
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]

    private let queue = DispatchQueue(label: "com.yyhsiu.cue.clipboard", qos: .utility)
    private let name: NSPasteboard.Name
    private let onEvent: @Sendable (Event) -> Void
    private var timer: DispatchSourceTimer?
    private var pasteboard: NSPasteboard?
    private var lastChange = 0
    private var generation = 0
    private var reportedDenial = false

    init(name: NSPasteboard.Name = .general, onEvent: @escaping @Sendable (Event) -> Void) {
        self.name = name
        self.onEvent = onEvent
    }

    func setEnabled(_ enabled: Bool, generation: Int) {
        queue.async { [self] in
            timer?.cancel()
            timer = nil
            self.generation = generation
            reportedDenial = false
            guard enabled else { pasteboard = nil; return }
            let board = NSPasteboard(name: name)
            pasteboard = board
            // Start with future copies, including after resuming. Never import stale contents.
            lastChange = board.changeCount
            let source = DispatchSource.makeTimerSource(queue: queue)
            source.schedule(deadline: .now() + .milliseconds(400), repeating: .milliseconds(400),
                            leeway: .milliseconds(80))
            source.setEventHandler { [weak self] in self?.poll() }
            timer = source
            source.resume()
        }
    }

    func resetBaseline(generation: Int) {
        queue.async { [self] in
            self.generation = generation
            if let pasteboard { lastChange = pasteboard.changeCount }
        }
    }

    func pollNow() { queue.async { [weak self] in self?.poll() } }

    /// A queue barrier for deterministic lifecycle checks; never used on the input path.
    func waitForPendingWork() async {
        await withCheckedContinuation { continuation in
            queue.async { continuation.resume() }
        }
    }

    private func poll() {
        guard let board = pasteboard else { return }
        autoreleasepool {
            if #available(macOS 15.4, *), board.accessBehavior == .alwaysDeny {
                if !reportedDenial {
                    reportedDenial = true
                    onEvent(.accessDenied(generation: generation))
                }
                lastChange = board.changeCount
                return
            }
            let change = board.changeCount
            guard change != lastChange else { return }
            lastChange = change
            let types = board.types ?? []
            guard !types.contains(where: { Self.ignoredTypes.contains($0.rawValue) }),
                  !types.contains(.fileURL) else { return }
            let type: NSPasteboard.PasteboardType
            if types.contains(.string) { type = .string }
            else if types.contains(.URL) { type = .URL }
            else { return }
            guard let value = board.string(forType: type),
                  board.changeCount == change,
                  value.utf8.count <= ClipboardStore.maximumEntryBytes,
                  !value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
            reportedDenial = false
            onEvent(.captured(value, generation: generation))
        }
    }
}
