import AppKit
import CueCore

struct LinkCleaningPreparation: Sendable {
    let result: LinkCleaner.Result
    let changeCount: Int
    let representations: [(NSPasteboard.PasteboardType, Data)]

    init(result: LinkCleaner.Result, changeCount: Int,
         representations: [(NSPasteboard.PasteboardType, Data)] = []) {
        self.result = result
        self.changeCount = changeCount
        self.representations = representations
    }
}

protocol LinkCleaning: Sendable {
    func prepare() async throws -> LinkCleaningPreparation
    func commit(_ preparation: LinkCleaningPreparation) async throws
}

enum LinkCleaningError: Error {
    case emptyClipboard, accessDenied, clipboardChanged, unsupportedContent, writeFailed
}

/// Promised clipboard data can wait on another app. Keep all clipboard access
/// and URL processing on this actor, outside the launcher's input/rendering path.
actor LinkCleaningService: LinkCleaning {
    private let pasteboardName: NSPasteboard.Name
    private static let maximumBackupBytes = 16 * 1_024 * 1_024
    private static let privacyMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping",
        "Pasteboard generator type",
    ]

    init(pasteboardName: NSPasteboard.Name = .general) {
        self.pasteboardName = pasteboardName
    }

    func prepare() throws -> LinkCleaningPreparation {
        try Task.checkCancellation()
        let board = NSPasteboard(name: pasteboardName)
        try checkAccess(board)
        let change = board.changeCount
        guard let items = board.pasteboardItems, !items.isEmpty else { throw LinkCleaningError.emptyClipboard }
        guard items.count == 1, let item = items.first,
              !item.types.contains(.fileURL) else { throw LinkCleaningError.unsupportedContent }
        guard item.types.contains(.string) || item.types.contains(.URL) else {
            throw LinkCleaningError.unsupportedContent
        }
        let value: String?
        if item.types.contains(.string) { value = item.string(forType: .string) }
        else { value = item.string(forType: .URL) }
        try Task.checkCancellation()
        guard board.changeCount == change else { throw LinkCleaningError.clipboardChanged }
        guard let value, !value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            throw LinkCleaningError.emptyClipboard
        }
        let result = try LinkCleaner.clean(value)
        // Already clean and signed URLs leave every original format untouched.
        guard result.removedParameterCount > 0 else {
            return LinkCleaningPreparation(result: result, changeCount: change)
        }
        guard item.types.count <= 32 else { throw LinkCleaningError.unsupportedContent }
        var backup: [(NSPasteboard.PasteboardType, Data)] = []
        var bytes = 0
        for type in item.types {
            try Task.checkCancellation()
            guard let data = item.data(forType: type), data.count <= Self.maximumBackupBytes - bytes else {
                throw LinkCleaningError.unsupportedContent
            }
            bytes += data.count
            backup.append((type, data))
        }
        guard board.changeCount == change else { throw LinkCleaningError.clipboardChanged }
        return LinkCleaningPreparation(result: result, changeCount: change, representations: backup)
    }

    func commit(_ preparation: LinkCleaningPreparation) throws {
        try Task.checkCancellation()
        guard preparation.result.removedParameterCount > 0, !preparation.result.isProtected else { return }
        let board = NSPasteboard(name: pasteboardName)
        try checkAccess(board)
        let item = NSPasteboardItem()
        guard item.setString(preparation.result.url, forType: .string),
              item.setString(preparation.result.url, forType: .URL) else { throw LinkCleaningError.writeFailed }
        // Replace stale rich-text links, but retain privacy hints respected by
        // clipboard managers. Ordinary clean copies follow the user's history setting.
        for (type, data) in preparation.representations where Self.privacyMarkers.contains(type.rawValue) {
            guard item.setData(data, forType: type) else { throw LinkCleaningError.writeFailed }
        }
        try Task.checkCancellation()
        guard board.changeCount == preparation.changeCount else { throw LinkCleaningError.clipboardChanged }
        // No suspension between the last cancellation/version check and publication.
        let clearCount = board.clearContents()
        guard board.writeObjects([item]) else {
            if board.changeCount == clearCount {
                let original = NSPasteboardItem()
                for (type, data) in preparation.representations { original.setData(data, forType: type) }
                _ = board.writeObjects([original])
            }
            throw LinkCleaningError.writeFailed
        }
    }

    private func checkAccess(_ board: NSPasteboard) throws {
        if #available(macOS 15.4, *), board.accessBehavior == .alwaysDeny {
            throw LinkCleaningError.accessDenied
        }
    }
}
