import AppKit
import Carbon
import CueCore

/// Integration checks use only synthetic content, unique named pasteboards,
/// isolated preferences, temporary history files, and offscreen AppKit views.
/// Never use the general pasteboard, post keys, or activate/show a window here.
@main
struct CheckClipboard {
    @MainActor
    static func main() async {
        let application = NSApplication.shared
        application.setActivationPolicy(.prohibited)
        application.mainMenu = nil
        let checks = Checks()
        do {
            try await checkMonitor(checks)
            try await checkModelAndView(checks)
            try await checkNumberKeys(checks)
            try await checkDeleteKeys(checks)
            try await checkExpiryOnOpen(checks)
            try await checkTermination(checks)
        } catch {
            checks.expect(false, "Unexpected fixture/setup failure: \(type(of: error))")
        }
        checks.expect(!application.isActive, "Checks must not activate the application")
        if !checks.failures.isEmpty {
            checks.failures.forEach { print("FAIL: \($0)") }
            print("Clipboard regression failed: \(checks.failures.count) failures / \(checks.count) checks.")
            exit(1)
        }
        print("Clipboard regression passed: \(checks.count) checks; capture privacy, lifecycle, persistence, async copy, retention, and native keyboard routing. Only isolated named pasteboards were used.")
    }

    @MainActor
    private static func checkMonitor(_ checks: Checks) async throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }
        let events = Events()
        let monitor = ClipboardMonitor(name: fixture.board.name) { events.append($0) }
        try fixture.write("Before enabling")
        monitor.setEnabled(true, generation: 1)
        await monitor.waitForPendingWork()
        monitor.pollNow()
        await monitor.waitForPendingWork()
        checks.expect(events.captures.isEmpty, "Enabling must not import existing clipboard contents")

        try fixture.write("Synthetic text\nwith exact whitespace  ")
        monitor.pollNow()
        await monitor.waitForPendingWork()
        checks.expect(events.captures.last?.text == "Synthetic text\nwith exact whitespace  ",
                      "Text capture must preserve original content")
        checks.expect(events.captures.last?.generation == 1, "Capture must carry the active generation")
        try fixture.write("https://example.invalid/clipboard-fixture", type: .URL)
        monitor.pollNow()
        await monitor.waitForPendingWork()
        checks.expect(events.captures.last?.text == "https://example.invalid/clipboard-fixture",
                      "A URL-only pasteboard must be captured")
        let afterURL = events.captures.count
        monitor.pollNow()
        await monitor.waitForPendingWork()
        checks.expect(events.captures.count == afterURL, "An unchanged pasteboard must not be captured twice")

        let skippedMarkers = [
            ClipboardMonitor.ownMarker.rawValue,
            "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
            "de.petermaurer.TransientPasteboardType", "com.typeit4me.clipping",
            "Pasteboard generator type", NSPasteboard.PasteboardType.fileURL.rawValue,
        ]
        for marker in skippedMarkers {
            try fixture.write("Synthetic skipped content", marker: NSPasteboard.PasteboardType(marker))
            monitor.pollNow()
            await monitor.waitForPendingWork()
            checks.expect(events.captures.count == afterURL, "Marker \(marker) must suppress text capture")
        }
        for (label, value) in [("blank", " \n\t"), ("oversize", String(repeating: "x", count: ClipboardStore.maximumEntryBytes + 1))] {
            try fixture.write(value)
            monitor.pollNow()
            await monitor.waitForPendingWork()
            checks.expect(events.captures.count == afterURL, "\(label) text must not be captured")
        }
        try fixture.write("Unsupported synthetic content", type: .init("com.yyhsiu.cue.tests.unsupported"))
        monitor.pollNow()
        await monitor.waitForPendingWork()
        checks.expect(events.captures.count == afterURL, "Unsupported pasteboard representations must be ignored")

        try fixture.write("Deleted baseline")
        monitor.resetBaseline(generation: 2)
        await monitor.waitForPendingWork()
        monitor.pollNow()
        await monitor.waitForPendingWork()
        checks.expect(events.captures.count == afterURL, "Resetting after deletion must not recapture the baseline")
        try fixture.write("Fresh after baseline reset")
        monitor.pollNow()
        await monitor.waitForPendingWork()
        checks.expect(events.captures.last?.generation == 2, "Fresh captures must use the reset generation")

        monitor.setEnabled(false, generation: 3)
        await monitor.waitForPendingWork()
        let beforePause = events.captures.count
        try fixture.write("Copied while paused")
        monitor.pollNow()
        await monitor.waitForPendingWork()
        checks.expect(events.captures.count == beforePause, "Paused monitoring must not capture")
        monitor.setEnabled(true, generation: 4)
        await monitor.waitForPendingWork()
        monitor.pollNow()
        await monitor.waitForPendingWork()
        checks.expect(events.captures.count == beforePause, "Resuming must skip copies made while paused")
        try fixture.write("Fresh after resume")
        monitor.pollNow()
        await monitor.waitForPendingWork()
        checks.expect(events.captures.count == beforePause + 1 && events.captures.last?.generation == 4,
                      "Resuming must capture the next fresh copy with its new generation")
        try fixture.write("Captured by the timer")
        await checks.eventually("The background timer must capture a fresh copy without a manual poll") {
            events.captures.last?.text == "Captured by the timer"
        }
        monitor.setEnabled(false, generation: 5)
        await monitor.waitForPendingWork()
        checks.expect(events.denials == 0, "The isolated named pasteboard must remain accessible")
    }

    @MainActor
    private static func checkModelAndView(_ checks: Checks) async throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }
        let seed = ClipboardStore(fileURL: fixture.file)
        _ = try await seed.record(text: "Alpha fixture", retention: .forever, now: Date().addingTimeInterval(-20))
        _ = try await seed.record(text: "Beta fixture", retention: .forever, now: Date().addingTimeInterval(-10))
        let model = ClipboardModel(defaults: fixture.defaults, fileURL: fixture.file, pasteboardName: fixture.board.name)
        defer { model.close(); model.stop() }
        checks.expect(!model.recordingEnabled, "Recording must be opt-in for new preferences")
        checks.expect(model.retention == .week, "Default retention must be one week")
        await checks.eventually("Model must finish loading synthetic history") { !model.isLoading }
        checks.expect(model.errorMessage == nil, "A valid history file must load without errors")
        var copies = 0
        var backs = 0
        let view = ClipboardView(model: model, onCopy: { index in model.copySelected(at: index) { copies += 1 } }, onBack: { backs += 1 })
        let window = NSPanel(contentRect: view.frame, styleMask: [.borderless, .nonactivatingPanel], backing: .buffered, defer: false)
        window.isReleasedWhenClosed = false
        window.contentView = view
        defer { window.contentView = nil; window.close() }

        model.open()
        await checks.eventually("Opening must display loaded history") { model.results.count == 2 && model.selectedEntry != nil }
        view.searchField.stringValue = "Alpha"
        view.controlTextDidChange(Notification(name: NSControl.textDidChangeNotification, object: view.searchField))
        checks.expect(model.query == "Alpha", "Typing must update the model synchronously")
        checks.expect(model.selectedEntry == nil, "A new query must invalidate the old selection immediately")
        let detachedEditor = NSTextView()
        checks.expect(view.control(view.searchField, textView: detachedEditor, doCommandBy: #selector(NSResponder.insertNewline(_:))),
                      "Return must be handled even before new search results arrive")
        await checks.eventually("Immediate query then Return must complete one copy") { copies == 1 }
        checks.expect(fixture.board.string(forType: .string) == "Alpha fixture", "Immediate Return must copy the current query's match")
        checks.expect(fixture.board.types?.contains(ClipboardMonitor.ownMarker) == true, "Copies must carry Cue's marker to avoid self-capture")

        // open() also queues pruning; that refresh must not cancel a user's copy.
        model.close()
        model.open()
        model.setQuery("Al")
        model.setQuery("not a match")
        model.setQuery("Beta")
        model.copySelected { copies += 1 }
        await checks.eventually("Rapid query changes plus an opening refresh must not swallow Return") { copies == 2 }
        checks.expect(fixture.board.string(forType: .string) == "Beta fixture", "Rapid query changes must copy only the latest query")
        await checks.eventually("Only the latest query may render") { model.results.count == 1 && model.results.first?.text == "Beta fixture" }

        try fixture.write("Unchanged after close")
        let beforeClose = fixture.board.changeCount
        model.setQuery("Alpha")
        model.copySelected { copies += 1 }
        model.close()
        model.open()
        await checks.eventually("Reopening must complete a fresh presentation search") { model.query.isEmpty && model.results.count == 2 && model.selectedEntry != nil }
        checks.expect(copies == 2 && fixture.board.changeCount == beforeClose, "Closing/reopening must invalidate a pending copy and callback")

        try fixture.write("Unchanged after query cancellation")
        let beforeQuery = fixture.board.changeCount
        model.setQuery("Alpha")
        model.copySelected { copies += 1 }
        model.setQuery("Beta")
        await checks.eventually("A newer query must settle after a canceled copy") { model.results.count == 1 && model.results.first?.text == "Beta fixture" }
        checks.expect(copies == 2 && fixture.board.changeCount == beforeQuery, "Changing the query must cancel an older copy request")

        model.setQuery("")
        await checks.eventually("Clearing query must restore both choices") { model.results.count == 2 && model.selectedEntry != nil }
        let alpha = model.results.first { $0.text == "Alpha fixture" }!
        model.select(alpha.id)
        model.copySelected { copies += 1 }
        await checks.eventually("Copying an explicitly selected older row must succeed") { copies == 3 }
        checks.expect(fixture.board.string(forType: .string) == alpha.text, "Copy must preserve explicit selection instead of choosing the first match")

        checkKeyboard(checks, model: model, view: view, window: window, backs: { backs })
        model.setQuery("")
        await checks.eventually("Keyboard checks must leave the original history searchable") { model.results.count == 2 && model.selectedEntry != nil }
        model.select(alpha.id)
        let handledDelete = view.performKeyEquivalent(with: key(window, "\u{7f}", code: UInt16(kVK_Delete)))
        checks.expect(handledDelete && !model.results.contains { $0.id == alpha.id }, "Command-Delete must remove the selected row immediately")
        await checks.eventuallyAsync("Deletion must persist to disk") {
            let disk = try? await ClipboardStore(fileURL: fixture.file).load(retention: .forever)
            return disk?.count == 1 && disk?.contains(where: { $0.id == alpha.id }) == false
        }
        // Keep pending monitor work inert while testing ordered mutations and deduplication.
        model.setRecordingEnabled(true)
        checks.expect(fixture.defaults.bool(forKey: "clipboard.recordingEnabled"), "The recording preference must persist in its isolated suite")
        model.setQuery("Beta")
        await checks.eventually("Remaining item must be selectable") { model.selectedEntry?.text == "Beta fixture" }
        let betaID = model.selectedID
        model.copySelected { copies += 1 }
        await checks.eventually("Recopying a retained item while recording must complete") { copies == 4 }
        await checks.eventuallyAsync("Recopy must deduplicate, preserve identity, and persist updated recency") {
            let disk = try? await ClipboardStore(fileURL: fixture.file).load(retention: .forever)
            return disk?.count == 1 && disk?.first?.id == betaID && (disk?.first?.copiedAt.timeIntervalSinceNow ?? -99) > -3
        }
        model.setRecordingEnabled(false)
        model.setRetention(.forever)
        checks.expect(!fixture.defaults.bool(forKey: "clipboard.recordingEnabled") && fixture.defaults.string(forKey: "clipboard.retention") == "forever",
                      "Pause and retention choices must persist")
        checks.expect(!window.isVisible, "Native keyboard checks must never show their window")
    }

    @MainActor
    private static func checkKeyboard(_ checks: Checks, model: ClipboardModel, view: ClipboardView, window: NSWindow, backs: () -> Int) {
        for event in [key(window), key(window, modifiers: [.command, .capsLock]), key(window, "，"), key(window, code: 47)] {
            let query = model.query
            checks.expect(view.handleSettingsShortcut(event) && view.isShowingSettings, "Command-comma must open feature settings synchronously")
            checks.expect(model.query == query, "Opening feature settings must preserve the search query")
            checks.expect(view.handleSettingsShortcut(key(window, repeated: true)) && view.isShowingSettings, "Key repeat must not toggle feature settings again")
            let previousBacks = backs()
            view.cancelOperation(nil)
            checks.expect(!view.isShowingSettings && backs() == previousBacks, "Escape must close feature settings before navigating back")
        }
        for event in [key(window, modifiers: []), key(window, modifiers: [.command, .shift]),
                      key(window, modifiers: [.command, .option]), key(window, modifiers: [.command, .control]),
                      key(window, "x", modifiers: [], code: 7)] {
            checks.expect(!view.handleSettingsShortcut(event) && !view.isShowingSettings, "Ordinary typing and modified shortcut near misses must remain normal input")
        }
        let previousBacks = backs()
        view.cancelOperation(nil)
        checks.expect(backs() == previousBacks + 1, "Escape from history must navigate back once")
        window.makeFirstResponder(view.searchField)
        guard let editor = view.searchField.currentEditor() as? NSTextView else {
            checks.expect(false, "AppKit must provide a real offscreen field editor for IME checks")
            return
        }
        editor.setMarkedText("注音", selectedRange: NSRange(location: 2, length: 0), replacementRange: NSRange(location: NSNotFound, length: 0))
        checks.expect(editor.hasMarkedText(), "IME fixture must have marked text")
        let beforeIME = model.results.map(\.id)
        for command in [#selector(NSResponder.insertNewline(_:)), #selector(NSResponder.moveDown(_:)), #selector(NSResponder.cancelOperation(_:))] {
            checks.expect(!view.control(view.searchField, textView: editor, doCommandBy: command), "IME composition must retain Return, arrows, and Escape")
        }
        checks.expect(!view.performKeyEquivalent(with: key(window, "\u{7f}", code: UInt16(kVK_Delete))), "Command-Delete must not delete history during IME composition")
        checks.expect(model.results.map(\.id) == beforeIME, "IME command routing must not mutate history")
        checks.expect(view.handleSettingsShortcut(key(window)) && view.isShowingSettings, "Command-comma during composition must remain in feature settings")
        editor.unmarkText()
        view.closeSettings()
    }

    @MainActor
    private static func checkDeleteKeys(_ checks: Checks) async throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }
        let seed = ClipboardStore(fileURL: fixture.file)
        for index in 0..<8 {
            _ = try await seed.record(text: "Deletion fixture \(index)", retention: .forever,
                                      now: Date().addingTimeInterval(Double(index - 20)))
        }
        let model = ClipboardModel(defaults: fixture.defaults, fileURL: fixture.file, pasteboardName: fixture.board.name)
        defer { model.close(); model.stop() }
        let view = ClipboardView(model: model, onCopy: { _ in }, onBack: {})
        let window = NSPanel(contentRect: view.frame, styleMask: [.borderless, .nonactivatingPanel], backing: .buffered, defer: false)
        window.isReleasedWhenClosed = false
        window.contentView = view
        defer { window.contentView = nil; window.close() }
        model.open()
        await checks.eventually("Delete-key fixture must display its saved entries") { model.results.count == 8 && model.selectedEntry != nil }
        view.layoutSubtreeIfNeeded()
        if let scroll = view.subviews.compactMap({ $0 as? NSScrollView }).first,
           let table = scroll.documentView as? NSTableView,
           let cell = table.view(atColumn: 0, row: 0, makeIfNecessary: true) as? NSTableCellView,
           let copiedAt = model.results.first?.copiedAt {
            let calendar = Calendar(identifier: .gregorian)
            let parts = calendar.dateComponents([.year, .month, .day, .hour, .minute, .second], from: copiedAt)
            let timestamp = String(format: "%04d-%02d-%02d %02d:%02d:%02d", parts.year!, parts.month!, parts.day!,
                                   parts.hour!, parts.minute!, parts.second!)
            let expected = L10n.format(ClipboardText.shared.copiedAt, timestamp)
            checks.expect(cell.subviews.compactMap { $0 as? NSTextField }.contains { $0.stringValue == expected },
                          "A rendered history cell must show the full copied date and time through seconds with its localized prefix")
        } else {
            checks.expect(false, "AppKit must create an offscreen history cell for the visible timestamp check")
        }

        let backward = key(window, "\u{7f}", modifiers: [], code: UInt16(kVK_Delete))
        let forward = key(window, "\u{f728}", modifiers: [.function], code: UInt16(kVK_ForwardDelete))
        let repeatedBackward = key(window, "\u{7f}", modifiers: [], code: UInt16(kVK_Delete), repeated: true)
        let repeatedForward = key(window, "\u{f728}", modifiers: [.function], code: UInt16(kVK_ForwardDelete), repeated: true)
        let editor = NSTextView()
        for (name, event, repeated) in [("Backspace", backward, repeatedBackward), ("forward Delete", forward, repeatedForward)] {
            let before = model.results.count
            let selected = model.selectedID
            checks.expect(view.performKeyEquivalent(with: event), "Empty-query \(name) must be consumed")
            checks.expect(model.results.count == before - 1 && !model.results.contains { $0.id == selected },
                          "One \(name) event must delete exactly the selected history row immediately")
            checks.expect(view.handleDeleteShortcut(repeated) && model.results.count == before - 1,
                          "Holding \(name) must consume repeats without deleting additional rows")
        }
        // These are independent command events. A handled key equivalent must not
        // also be dispatched to the field editor for the same physical key press.
        for command in [#selector(NSResponder.deleteBackward(_:)), #selector(NSResponder.deleteForward(_:))] {
            let before = model.results.count
            checks.expect(view.control(view.searchField, textView: editor, doCommandBy: command),
                          "The empty-query field-editor delete fallback must be handled")
            checks.expect(model.results.count == before - 1, "One field-editor delete command must remove exactly one row")
        }

        model.setQuery("Deletion")
        await checks.eventually("Filtered history must settle before normal editing checks") { model.results.count == 4 && model.selectedEntry != nil }
        let beforeEditing = model.results.map(\.id)
        for event in [backward, forward, repeatedBackward, repeatedForward] {
            checks.expect(!view.handleDeleteShortcut(event), "Plain deletion with a nonempty query must remain ordinary text editing")
        }
        for command in [#selector(NSResponder.deleteBackward(_:)), #selector(NSResponder.deleteForward(_:))] {
            checks.expect(!view.control(view.searchField, textView: editor, doCommandBy: command),
                          "A nonempty-query delete command must remain available to the field editor")
        }
        checks.expect(model.query == "Deletion" && model.results.map(\.id) == beforeEditing,
                      "Routing query-editing keys must not delete history or change the query itself")
        let selectedFiltered = model.selectedID
        checks.expect(view.handleDeleteShortcut(key(window, "\u{7f}", code: UInt16(kVK_Delete))),
                      "Command-Delete must remain available in filtered history")
        checks.expect(model.results.count == 3 && !model.results.contains { $0.id == selectedFiltered },
                      "Command-Delete must remove exactly the selected filtered row")

        model.setQuery("")
        await checks.eventually("Clearing the query must restore an active selection") { model.results.count == 3 && model.selectedEntry != nil }
        let beforeHeldKey = model.results.map(\.id)
        checks.expect(view.handleDeleteShortcut(repeatedBackward) && model.results.map(\.id) == beforeHeldKey,
                      "Continuing to hold Backspace after the final query character disappears must not delete history")
        let modifiedDeletes: [NSEvent.ModifierFlags] = [.option, .control, .shift, [.command, .shift]]
        for modifiers in modifiedDeletes {
            checks.expect(!view.handleDeleteShortcut(key(window, "\u{7f}", modifiers: modifiers, code: UInt16(kVK_Delete))),
                          "Modified deletion near misses must retain their normal editing behavior")
        }

        view.showFeatureSettings()
        for event in [backward, forward, key(window, "\u{7f}", code: UInt16(kVK_Delete))] {
            checks.expect(!view.handleDeleteShortcut(event), "Delete shortcuts must not act on history while feature settings are open")
        }
        for command in [#selector(NSResponder.deleteBackward(_:)), #selector(NSResponder.deleteForward(_:))] {
            checks.expect(!view.control(view.searchField, textView: editor, doCommandBy: command),
                          "The hidden search field must not delete history from feature settings")
        }
        checks.expect(model.results.map(\.id) == beforeHeldKey, "Settings deletion keys must leave all history intact")
        view.closeSettings()
        window.makeFirstResponder(view.searchField)
        if let fieldEditor = view.searchField.currentEditor() as? NSTextView {
            fieldEditor.setMarkedText("注音", selectedRange: NSRange(location: 2, length: 0),
                                      replacementRange: NSRange(location: NSNotFound, length: 0))
            checks.expect(fieldEditor.hasMarkedText(), "Delete-key IME fixture must contain marked text")
            for event in [backward, forward, key(window, "\u{7f}", code: UInt16(kVK_Delete))] {
                checks.expect(!view.handleDeleteShortcut(event), "Delete shortcuts must not interfere with marked text composition")
            }
            for command in [#selector(NSResponder.deleteBackward(_:)), #selector(NSResponder.deleteForward(_:))] {
                checks.expect(!view.control(view.searchField, textView: fieldEditor, doCommandBy: command),
                              "IME composition must retain field-editor backward and forward deletion")
            }
            checks.expect(model.results.map(\.id) == beforeHeldKey, "IME delete routing must leave history intact")
            fieldEditor.unmarkText()
        } else {
            checks.expect(false, "AppKit must provide an offscreen field editor for delete-key IME checks")
        }
        await model.prepareForTermination()
        let disk = try await ClipboardStore(fileURL: fixture.file).load(retention: .forever)
        checks.expect(disk.count == 3, "Only the five deliberate delete events may persist history changes")
        checks.expect(!window.isVisible, "Delete-key checks must not show a window")
    }

    @MainActor
    private static func checkNumberKeys(_ checks: Checks) async throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }
        let seed = ClipboardStore(fileURL: fixture.file)
        for index in 0..<20 {
            let group = index < 10 ? "A" : "B"
            _ = try await seed.record(text: String(format: "Group %@ fixture %02d", group, index % 10), retention: .forever,
                                      now: Date().addingTimeInterval(Double(index - 100)))
        }
        let model = ClipboardModel(defaults: fixture.defaults, fileURL: fixture.file, pasteboardName: fixture.board.name)
        defer { model.close(); model.stop() }
        var requests = 0
        var copies = 0
        let view = ClipboardView(model: model, onCopy: { index in
            requests += 1
            model.copySelected(at: index) { copies += 1 }
        }, onBack: {})
        let window = NSPanel(contentRect: view.frame, styleMask: [.borderless, .nonactivatingPanel], backing: .buffered, defer: false)
        window.isReleasedWhenClosed = false
        window.contentView = view
        defer { window.contentView = nil; window.close() }
        model.open()
        await checks.eventually("Number-key clipboard fixture must show only its nine newest matches") { model.results.count == 9 && model.selectedEntry != nil }
        let firstKey = key(window, "1", code: 18)
        let ninthKey = key(window, "9", code: 25)
        model.select(model.results.last?.id)
        checks.expect(view.performKeyEquivalent(with: firstKey) && requests == 1,
                      "Command-1 must request immediate execution instead of only selecting a row")
        await checks.eventually("The first numbered copy must complete exactly once") { copies == 1 }
        checks.expect(fixture.board.string(forType: .string) == "Group B fixture 09",
                      "Command-1 must copy the first visible result regardless of the prior selection")
        checks.expect(view.performKeyEquivalent(with: ninthKey) && requests == 2,
                      "Command-9 must request the ninth result immediately")
        await checks.eventually("The ninth numbered copy must complete exactly once") { copies == 2 }
        checks.expect(fixture.board.string(forType: .string) == "Group B fixture 01", "Command-9 must copy the ninth visible result")
        for event in [key(window, "1", code: 18, repeated: true), key(window, "9", code: 25, repeated: true)] {
            checks.expect(view.handleNumberShortcut(event) && requests == 2,
                          "Holding a numbered shortcut must consume repeats without requesting another copy")
        }
        view.layoutSubtreeIfNeeded()
        if let scroll = view.subviews.compactMap({ $0 as? NSScrollView }).first,
           let table = scroll.documentView as? NSTableView {
            checks.expect(!scroll.hasVerticalScroller && !scroll.hasHorizontalScroller,
                          "Clipboard history must never create a scrollbar when saved history exceeds nine items")
            checks.expect(table.numberOfRows == 9 && view.tableView(table, viewFor: table.tableColumns.first, row: 9) == nil,
                          "Only the nine numbered clipboard matches may be rendered")
            for row in [0, 8] {
                let cell = view.tableView(table, viewFor: table.tableColumns.first, row: row)
                checks.expect(cell?.subviews.compactMap { $0 as? NSTextField }.contains { $0.stringValue == ResultShortcut.label(for: row) } == true,
                              "Rendered clipboard row \(row + 1) must show the matching number label")
            }
        } else {
            checks.expect(false, "Clipboard must expose an offscreen table for numbered-label checks")
        }
        let modifiers: [NSEvent.ModifierFlags] = [[], [.command, .shift], [.command, .option], [.command, .control]]
        for flags in modifiers {
            checks.expect(!view.handleNumberShortcut(key(window, "1", modifiers: flags, code: 18)),
                          "Ordinary number typing and modified near misses must not copy history")
        }
        checks.expect(!view.handleNumberShortcut(key(window, "0", code: 29)) && requests == 2,
                      "Command-0 and other number near misses must not request a copy")
        view.showFeatureSettings()
        checks.expect(!view.handleNumberShortcut(firstKey) && requests == 2,
                      "Numbered shortcuts must not copy from behind clipboard settings")
        view.closeSettings()
        window.makeFirstResponder(view.searchField)
        if let editor = view.searchField.currentEditor() as? NSTextView {
            editor.setMarkedText("注音", selectedRange: NSRange(location: 2, length: 0),
                                 replacementRange: NSRange(location: NSNotFound, length: 0))
            checks.expect(editor.hasMarkedText(), "Clipboard numbered-key IME fixture must have marked text")
            checks.expect(!view.handleNumberShortcut(firstKey) && requests == 2 && editor.hasMarkedText(),
                          "Numbered shortcuts must preserve IME composition without requesting a copy")
            editor.unmarkText()
        } else {
            checks.expect(false, "AppKit must provide an offscreen field editor for numbered-key IME checks")
        }

        // Do not yield between typing and Command-9. Old displayed results have
        // the same number of entries, but the correct new-query ninth item differs.
        model.setQuery("Group B")
        model.setQuery("Group A")
        checks.expect(view.handleNumberShortcut(ninthKey) && requests == 3,
                      "A numbered action immediately after typing must not wait for displayed search results")
        await checks.eventually("Immediate numbered copy must resolve the latest query") { copies == 3 }
        checks.expect(fixture.board.string(forType: .string) == "Group A fixture 01",
                      "Rapid query then Command-9 must copy the new query's ninth result, never a stale row")
        await checks.eventually("The latest numbered-copy query must remain visible within the nine-row limit") { model.results.count == 9 && model.results.first?.text == "Group A fixture 09" }
        checks.expect(view.handleNumberShortcut(key(window, "1", modifiers: [.command, .capsLock], code: 18)),
                      "Caps Lock must not disable clipboard numbered shortcuts")
        await checks.eventually("Numbered copy with Caps Lock must execute once") { copies == 4 }
        checks.expect(fixture.board.string(forType: .string) == "Group A fixture 09", "Command-1 must use the current filtered first result")

        model.setQuery("Group A fixture 00")
        await checks.eventually("Searching must find a stored record outside both the newest nine and the first nine group matches") {
            model.results.count == 1 && model.selectedEntry?.text == "Group A fixture 00"
        }
        try fixture.write("Unchanged by missing number")
        let beforeMissing = fixture.board.changeCount
        _ = view.handleNumberShortcut(ninthKey)
        // Allow the asynchronous negative result to complete without closing or
        // changing the query, which could mask an erroneous numbered-copy request.
        try await Task.sleep(for: .milliseconds(40))
        checks.expect(copies == 4 && fixture.board.changeCount == beforeMissing,
                      "A nonexistent numbered result must neither copy another row nor call completion")
        model.setQuery("Group B")
        _ = view.handleNumberShortcut(firstKey)
        model.close()
        model.open()
        await checks.eventually("Reopening after a canceled numbered action must restore nine visible history entries") { model.query.isEmpty && model.results.count == 9 && model.selectedEntry != nil }
        checks.expect(copies == 4 && fixture.board.changeCount == beforeMissing,
                      "Closing and reopening must cancel a pending numbered copy")
        let beforeDeletion = try await ClipboardStore(fileURL: fixture.file).load(retention: .forever)
        checks.expect(beforeDeletion.count == 20, "Limiting visible history must preserve every saved record")
        let removedID = model.selectedID
        model.removeSelected()
        checks.expect(model.results.count == 8 && !model.results.contains { $0.id == removedID },
                      "Deleting from a full nine-row list must acknowledge the action immediately")
        await checks.eventually("Deleting must refill the ninth slot from retained history") {
            model.results.count == 9 && !model.results.contains { $0.id == removedID }
                && model.results.last?.text == "Group B fixture 00"
        }
        await model.prepareForTermination()
        let disk = try await ClipboardStore(fileURL: fixture.file).load(retention: .forever)
        checks.expect(disk.count == 19 && !disk.contains { $0.id == removedID },
                      "Only the explicitly deleted record may be removed from full history")
        checks.expect(!window.isVisible, "Numbered clipboard tests must not show a window")
    }

    @MainActor
    private static func checkExpiryOnOpen(_ checks: Checks) async throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }
        fixture.defaults.set("hour", forKey: "clipboard.retention")
        let expiration = Date().addingTimeInterval(0.7)
        _ = try await ClipboardStore(fileURL: fixture.file).record(text: "Expiring synthetic item", retention: .forever,
                                                                 now: expiration.addingTimeInterval(-3600))
        let model = ClipboardModel(defaults: fixture.defaults, fileURL: fixture.file, pasteboardName: fixture.board.name)
        defer { model.close(); model.stop() }
        await checks.eventually("Expiry fixture must load before its deadline") { !model.isLoading }
        model.open()
        await checks.eventually("A not-yet-expired item must initially be visible", timeout: 0.4) { model.results.count == 1 }
        model.close()
        // This is an actual retention boundary, not an artificial production delay.
        while Date() <= expiration { try await Task.sleep(for: .milliseconds(15)) }
        model.open()
        await checks.eventually("Opening must expire old entries even while recording is paused") { model.results.isEmpty && model.selectedID == nil }
        await checks.eventuallyAsync("Opening-time retention cleanup must persist") {
            (try? await ClipboardStore(fileURL: fixture.file).load(retention: .forever).isEmpty) == true
        }
    }

    @MainActor
    private static func checkTermination(_ checks: Checks) async throws {
        let fixture = try Fixture()
        defer { fixture.cleanUp() }
        let seed = ClipboardStore(fileURL: fixture.file)
        _ = try await seed.record(text: "Retained on quit", retention: .forever, now: Date().addingTimeInterval(-20))
        _ = try await seed.record(text: "Deleted immediately before quit", retention: .forever, now: Date().addingTimeInterval(-10))
        let model = ClipboardModel(defaults: fixture.defaults, fileURL: fixture.file, pasteboardName: fixture.board.name)
        defer { model.close(); model.stop() }
        model.open()
        await checks.eventually("Termination fixture must display both saved items") { model.results.count == 2 && model.selectedEntry != nil }
        let deletedID = model.selectedID
        try fixture.write("Unchanged during termination")
        let beforeQuit = fixture.board.changeCount
        var copies = 0

        model.removeSelected()
        checks.expect(model.results.count == 1, "Deletion immediately before quitting must acknowledge the action synchronously")
        model.copySelected { copies += 1 }
        // Do not poll the file or yield between deletion and shutdown: shutdown
        // itself must drain the accepted mutation and cancel the pending copy.
        await model.prepareForTermination()
        let disk = try await ClipboardStore(fileURL: fixture.file).load(retention: .forever)
        checks.expect(disk.count == 1 && !disk.contains { $0.id == deletedID }, "Immediate quit must persist a queued deletion before returning")
        checks.expect(disk.first?.text == "Retained on quit", "Shutdown must preserve other retained items")
        checks.expect(copies == 0 && fixture.board.changeCount == beforeQuit, "Shutdown must cancel pending clipboard writes and their callbacks")
        model.open()
        model.copySelected { copies += 1 }
        await model.prepareForTermination()
        checks.expect(copies == 0 && fixture.board.changeCount == beforeQuit, "A repeated shutdown or late invocation must not restart clipboard interaction")
    }

    @MainActor
    private static func key(_ window: NSWindow, _ characters: String = ",", modifiers: NSEvent.ModifierFlags = .command,
                            code: UInt16 = UInt16(kVK_ANSI_Comma), repeated: Bool = false) -> NSEvent {
        NSEvent.keyEvent(with: .keyDown, location: .zero, modifierFlags: modifiers, timestamp: 0,
                        windowNumber: window.windowNumber, context: nil, characters: characters,
                        charactersIgnoringModifiers: characters, isARepeat: repeated, keyCode: code)!
    }
}

@MainActor
private final class Checks {
    var count = 0
    var failures: [String] = []

    func expect(_ condition: Bool, _ message: String) {
        count += 1
        if !condition { failures.append(message) }
    }

    func eventually(_ message: String, timeout: TimeInterval = 3, _ condition: () -> Bool) async {
        let deadline = Date().addingTimeInterval(timeout)
        while !condition(), Date() < deadline { try? await Task.sleep(for: .milliseconds(15)) }
        expect(condition(), message)
    }

    func eventuallyAsync(_ message: String, _ condition: () async -> Bool) async {
        let deadline = Date().addingTimeInterval(3)
        var passed = await condition()
        while !passed, Date() < deadline {
            try? await Task.sleep(for: .milliseconds(15))
            passed = await condition()
        }
        expect(passed, message)
    }
}

private final class Events: @unchecked Sendable {
    struct Capture { let text: String; let generation: Int }
    private let lock = NSLock()
    private var values: [Capture] = []
    private var denialCount = 0

    var captures: [Capture] { lock.withLock { values } }
    var denials: Int { lock.withLock { denialCount } }

    func append(_ event: ClipboardMonitor.Event) {
        lock.withLock {
            switch event {
            case .captured(let text, let generation): values.append(Capture(text: text, generation: generation))
            case .accessDenied: denialCount += 1
            }
        }
    }
}

@MainActor
private final class Fixture {
    enum Failure: Error { case write }
    let directory: URL
    let file: URL
    let suite: String
    let defaults: UserDefaults
    let board: NSPasteboard

    init() throws {
        let id = UUID().uuidString
        suite = "com.yyhsiu.cue.tests.clipboard.\(id)"
        defaults = UserDefaults(suiteName: suite)!
        directory = FileManager.default.temporaryDirectory.appendingPathComponent("cue-clipboard-fixture-\(id)", isDirectory: true)
        file = directory.appendingPathComponent("history.json")
        board = NSPasteboard(name: NSPasteboard.Name(suite))
        precondition(board.name != .general)
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: false)
    }

    func write(_ text: String, type: NSPasteboard.PasteboardType = .string, marker: NSPasteboard.PasteboardType? = nil) throws {
        if marker?.rawValue == "Pasteboard generator type" {
            // Historical pasteboard names are accepted by the owner API, while
            // NSPasteboardItem only permits UTI names for new representations.
            board.declareTypes([type, marker!], owner: nil)
            guard board.setString(text, forType: type), board.setData(Data(), forType: marker!),
                  board.types?.contains(marker!) == true else { throw Failure.write }
            return
        }
        let item = NSPasteboardItem()
        item.setString(text, forType: type)
        if let marker { item.setData(Data(), forType: marker) }
        board.clearContents()
        guard board.writeObjects([item]) else { throw Failure.write }
    }

    func cleanUp() {
        board.releaseGlobally()
        defaults.removePersistentDomain(forName: suite)
        try? FileManager.default.removeItem(at: directory)
    }
}
